name: Playwright Tests
on:
  push:
    branches: main
  pull_request:
    branches: main

  # Allow updating snapshots during manual runs
  workflow_call:
    inputs:
      update-snapshots:
        description: 'Update snapshots?'
        type: boolean

  # Allow updating snapshots during automatic runs
  workflow_dispatch:
    inputs:
      update-snapshots:
        description: 'Update snapshots?'
        type: boolean
env:
  NEXT_PUBLIC_SITE_URL: ${{secrets.NEXT_PUBLIC_SITE_URL}}
  NEXT_PUBLIC_SITE_URL_PON: ${{secrets.NEXT_PUBLIC_SITE_URL_PON}}
  NEXT_PUBLIC_API_URL_PON: ${{secrets.NEXT_PUBLIC_API_URL_PON}}
  NEXT_PUBLIC_USER: ${{secrets.NEXT_PUBLIC_USER}}
  NEXT_PUBLIC_PASS: ${{secrets.NEXT_PUBLIC_PASS}}

jobs:
  playwright:
    name: 'Playwright Tests'
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.44.0-jammy
    strategy:
      matrix:
        browser: [chromium, firefox, webkit]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 8.6.7
      - name: Install dependencies
        run: pnpm install
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps ${{matrix.browser}}
      - name: Set up cache
        id: cache
        uses: actions/cache@v4
        with:
          key: cache/${{github.repository}}/${{github.ref}}
          restore-keys: cache/${{github.repository}}/refs/heads/main
          path: tests/**
      - name: Initialize snapshots
        if: ${{steps.cache.outputs.cache-hit != 'true' || inputs.update-snapshots == 'true'}}
        run: HOME=/root pnpm playwright test --project=${{matrix.browser}} --update-snapshots --reporter html
      - name: Test
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-${{matrix.browser}}
          path: tests/results/
          retention-days: 30
          overwrite: true
